name: myWoodbridge
description: Woodbridge Mobile Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+101

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_sticky_header: ^0.4.0
  table_calendar: ^1.2.2
  firebase_messaging: ^5.0.3
  flutter_plugin_pdf_viewer: ^1.0.7
  intl: ^0.15.8
  photo_view: ^0.4.2
  shared_preferences: ^0.5.3+3
  cached_network_image: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/background-img.png
    - img/woodbridge_logo.png
    - img/Icons/icon_payments_2x.png
    - img/Icons/icon_activities_2x.png
    - img/Icons/icon_attendance_2x.png
    - img/Icons/icon_grades_2x.png
    - img/Icons/icon_gallery_2x.png
    - img/Icons/icon_announcements_2x.png
    - img/Icons/Icon-180.png
    - img/home_profile_head_cover.png
    - img/mywoodbridge.png
    - files/TWAMobileParentsGuide.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
     - family: Muli
       fonts:
         - asset: fonts/Muli-Black.ttf
           weight: 800
         - asset: fonts/Muli-BlackItalic.ttf
         - asset: fonts/Muli-Bold.ttf
           weight: 600
         - asset: fonts/Muli-BoldItalic.ttf
         - asset: fonts/Muli-ExtraBold.ttf
           weight: 700
         - asset: fonts/Muli-ExtraBoldItalic.ttf
         - asset: fonts/Muli-ExtraLight.ttf
           weight: 200
         - asset: fonts/Muli-ExtraLightItalic.ttf
         - asset: fonts/Muli-Italic.ttf
         - asset: fonts/Muli-Light.ttf
           weight: 300
         - asset: fonts/Muli-LightItalic.ttf
         - asset: fonts/Muli-Regular.ttf
           weight: 400
         - asset: fonts/Muli-SemiBold.ttf
           weight: 500
         - asset: fonts/Muli-SemiBoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
