#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Volumes/Keen/Server/flutter"
export "FLUTTER_APPLICATION_PATH=/Volumes/Keen/Desk/Work/Stratium/Woodbridge/App/Flutter"
export "FLUTTER_TARGET=/Volumes/Keen/Desk/Work/Stratium/Woodbridge/App/Flutter/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Volumes/Keen/Server/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.6.1"
export "FLUTTER_BUILD_NUMBER=102"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
