#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Volumes/Keen/Room/Server/Flutter/flutter"
export "FLUTTER_APPLICATION_PATH=/Volumes/Keen/Desk/Career/Stratium/woodbridge-mobile"
export "FLUTTER_TARGET=/Volumes/Keen/Desk/Career/Stratium/woodbridge-mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Volumes/Keen/Room/Server/Flutter/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.7.3"
export "FLUTTER_BUILD_NUMBER=107"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
